# Online Configuration file
server:
  port: 8101
spring:
  # Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AIAnswering
    username: root
    password: 123456
  # Redis Configuration
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
mybatis-plus:
  configuration:
    # Production environment shutdown log
    log-impl: ''
# Interface Documentation Configuration
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
